### ISSUE TITLE
如何获取start方法的xml信息

### ISSUE THREAD

**Issue by itpPhange** [F-ca7/AsterMark#1]
如何获取start方法的xml信息

**Comment by F-ca7** [comment]
不好意思，之前修改界面忘记上传了。现在受疫情影响，代码还在另一台机器上，到时候会上传。

**Comment by westsince2001** [comment]
tks,也有同样的需求！

**Comment by dxshbb** [comment]
> 如何获取start方法的xml信息

您好，请问项目你跑起来了吗？想问下您怎么启动的

**Comment by dxshbb** [comment]
> 不好意思，之前修改界面忘记上传了。现在受疫情影响，代码还在另一台机器上，到时候会上传。

请问现在能传下吗，相关代码，麻烦您了！

**Comment by F-ca7** [comment]
上传了gui资源，由于目前找到的不是最新版本的文件，有些新功能可能丢失了，比如支持不同数据库的类型（比如 mysql、pg、sqlserver）；在gui包下的Main类即可启动。
