### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Hugo12333** [F-ca7/AsterMark#7]
大佬我想请问一下这个如何运行（需要这个项目可是学校没教java），需要配置什么环境，如何分解项目，如何找到exe可执行文件

**Comment by F-ca7** [comment]
1. 需要配置JDK1.8环境，如果你是Windows电脑可以搜索——Windows JRE1.8 配置
2. 项目结构你先需要了解Java项目通常的结构 与Java的包等概念，比如 `src/main/java` 是放置项目Java源代码的；项目整体可以分为以下几个部分：
    - gui用户界面
    - 内核模块
        - 数据库模块
        - 水印算法
        - 工具类等
3. 由于是Java项目，你可以搜索如何运行Java项目、也可以搜索如何把Java程序打包成exe，该项目并没有把这个程序打包为exe可执行文件

**Comment by Hugo12333** [comment]
好的谢谢，我已经在idea运行成功了，现在就是如何读懂代码，了解大体框架了
